### ISSUE TITLE
Moving from one area of elevated terrain to another sets elevation to 0

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevated-vision#10]
If you move a token from an area without elevated terrain to an area of elevated terrain the token gets set to the proper elevation but if you move from one area of elevated terrain to another, the elevation on the token gets set to 0. The correct elevation shows while hovering over the square, though.

Module version: 0.1alpha
dnd5e 2.0.3
Foundry 10.286

**Comment by caewok** [comment]
Fixed in v0.1.0.
