### ISSUE TITLE
Some weirdness with shadows in certain circumstances

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevated-vision#11]
Take this situation for example. The token is standing on a 55 high elevation. The wall next to him is 50 feet tall but it prevents him from seeing a bunch of area in front on him. With the module disabled he can see the area fine.

![image](https://user-images.githubusercontent.com/12570777/193134921-01c1b71d-1e7b-40e3-bc93-5c8cdedd67de.png)
![image](https://user-images.githubusercontent.com/12570777/193134962-64293b0d-d2d6-4ddf-9bbf-e2ce6e4f4442.png)

**Comment by caewok** [comment]
Here is what I get when I re-construct that setup:

Walls:
<img width="739" alt="Screen Shot 2022-09-29 at 4 43 57 PM" src="https://user-images.githubusercontent.com/1267134/193160917-fbd266a7-4329-4872-a9ff-c941366b19f0.png">

Vision:
<img width="739" alt="Screen Shot 2022-09-29 at 4 43 52 PM" src="https://user-images.githubusercontent.com/1267134/193160924-47f511ca-b197-481c-a090-ef28d251efe7.png">

Hopefully you get a similar view, where the token can see beyond the 50' wall at some distance.

To me, that looks correct. If you are very close to a 20' wall, and you are at 55', the wall obscures very little of your vision. But if the wall is 50', it obscures a lot more of your vision. Note that the measure here is from the token center, so it is not like the token is literally peering over the wall. It comes down to trigonometry. Think about standing a bit back from the cliff on a mesa, and how you cannot see what is directly below the cliff edge. 

To improve this experience, the [Token Lean](https://github.com/WesBelmont/token-lean) module would be really useful, but it has not yet been updated for v10. I will see if I can fork it and submit a PR. That would let you temporarily move the center of the token for purposes of vision, and in fact allow it to "peer" over the wall.

**Comment by caewok** [comment]
Try this fork of Token Lean: https://github.com/caewok/token-lean/releases/tag/1.2.0

I have not tried to update its compatibility with Perfect Vision or Levels, but I got it to work in v10.

**Comment by Zamrod** [comment]
Token lean definitely helps, though it is rather difficult to target tokens when using it.

I'm wondering if the math for elevated vision assumes your eyes are 5 feet above your elevation like wall height does? Does it use the wall height token height setting?

**Comment by caewok** [comment]
Yes, the math pulls the same `losHeight` property that Wall Height calculates. By default, I believe that is 5'.

**Comment by caewok** [comment]
I should add that the detection test uses a 3d model of the token, assuming the token spans from its elevation to its losHeight. Thus, it is possible for a token to be seen even if otherwise in a shadow. For example, if token Alice is at 20', looking over a wall at 20', the wall casts a shadow. Token Bob, at 15', might be in that shadow but Alice can still see Bob's head at, say, 18.5'. This helps alleviate some of the targeting issues, but not always, as it would be height dependent. 

This is in part a Foundry UI issue—there should probably be a way for the player to target unseen tokens for various reasons. That difficulty is exacerbated by modules like this one  and Levels.

**Comment by caewok** [comment]
I am going to close this b/c the vision testing was moved to Alternate Token Visibility. And if Levels or PV is present, it will use those modules for visibility. Near as I can tell, shadow calculation is accurate.
