### ISSUE TITLE
Potential Issues with v10.286

### ISSUE THREAD

**Issue by Mystosin** [caewok/fvtt-elevated-vision#13]
With only Wall Height, libWrapper, and Elevated Vision enabled, none of my tokens with vision can see other tokens in the dark. Even if they have Darkvision enabled. As soon as a light source is added they can see. Also feel tremor detection does not work while this module is enabled.

**Comment by caewok** [comment]
Yes, there is something weird going on there. I will look into it; thanks!

**Comment by caewok** [comment]
In the meantime, if you uncheck "apply elevation data to token vision" in the Elevated Vision settings, I think it will work. Not sure about tremor detection, but at least normal vision rules should work.

**Comment by caewok** [comment]
Fixed in v0.1.1. May still need work with tremor detection. Could you open a new issue with some details about how you think tremor detection should work? Thanks!
