### ISSUE TITLE
Still Issues with token vision in complete darkness and Darkvision enabled.

### ISSUE THREAD

**Issue by Mystosin** [caewok/fvtt-elevated-vision#15]
Hello,

Even after the update still not working as expected.

This screenshot is with GM vision.
![Screenshot 2022-10-01 205241](https://user-images.githubusercontent.com/114778289/193434553-07da9b4e-f70b-4673-a1c7-f0310817dd4e.png)

This is the vision with darkvision in complete darkness.
![Screenshot 2022-10-01 205308](https://user-images.githubusercontent.com/114778289/193434561-e07a0043-3510-4a30-9012-f97d6db7e527.png)

Then this is with a dim light set to 5ft on the other token.
![Screenshot 2022-10-01 205345](https://user-images.githubusercontent.com/114778289/193434576-c4982767-35a2-47d7-910e-44b30193b486.png)

Active Modules.
![Screenshot 2022-10-01 205802](https://user-images.githubusercontent.com/114778289/193434611-3cff7dd3-4072-406a-ab29-94d8c6fb33aa.png)

Elevated Vision Settings.
![Screenshot 2022-10-01 205823](https://user-images.githubusercontent.com/114778289/193434615-b5cb6f57-d606-4f9a-9854-40111c4c65de.png)

**Comment by Mystosin** [comment]
Forgot to add this screenshot.

This is darkvision without Elevated Vision enabled.
![Screenshot 2022-10-01 210129](https://user-images.githubusercontent.com/114778289/193434670-8f124767-ae9d-44fe-aafa-e66f3384e018.png)

**Comment by caewok** [comment]
Is this still happening in v0.1.2?

**Comment by Mystosin** [comment]
Just tested it out and can confirm that both tremor sense and darkvision are working as expected.

**Comment by Mystosin** [comment]
Although a new issue has arisen. Now tokens without darkvision cannot see light sources in darkness. They can see tokens as though the light source is there but not the actual light itself.

**Comment by Mystosin** [comment]
I did discover that it is only happening when Apply elevation data to token vision is enabled.

Here is gm vision
![GM Vision](https://user-images.githubusercontent.com/114778289/193625889-620bd9f8-b692-4983-a998-852422b13ae8.png)

Token Vision
![Token Vison](https://user-images.githubusercontent.com/114778289/193625932-1394e13c-a87c-4798-a580-d846a6e514e7.png)

And Token Settings
![Token Settings](https://user-images.githubusercontent.com/114778289/193625981-ee9992b0-4e01-467c-8ab4-40540d7f16af.png)

But as I said it is only when that first setting is enabled.

**Comment by caewok** [comment]
Yep, I see what you mean. Thanks! I will look into it.

**Comment by caewok** [comment]
The temporary fix is to set the sight range for token vision to 0.01 instead of 0. I am working on a more permanent fix.

**Comment by caewok** [comment]
Fixed in v0.1.4
