### ISSUE TITLE
Terrain walls cast incorrect shadows

### ISSUE THREAD

**Issue by dev7355608** [caewok/fvtt-elevated-vision#37]
- Display Elevation Shadow: Polygons (if WebGL, this bug does not occur)
- Wall Height: Enabled (if disabled, this bug does not occur)

![image](https://user-images.githubusercontent.com/31905376/210020167-a427fc25-f21a-4c1d-bc63-58c370486f83.png)
![image](https://user-images.githubusercontent.com/31905376/210020196-4033f594-d7f3-4663-87f9-ffac1f7bea12.png)
![image](https://user-images.githubusercontent.com/31905376/210020258-6d9da200-c565-4a85-ad15-8ea61098e7b9.png)

### With Bottom/Top 0/1000:
![image](https://user-images.githubusercontent.com/31905376/210021022-8f33a2dc-4141-4186-86cf-8a289f5a0f0c.png)
![image](https://user-images.githubusercontent.com/31905376/210020975-f6d2762d-8d89-418e-a3a8-dccf5636ddd7.png)

**Comment by caewok** [comment]
Yes, terrain wall shadows were borked because an infinite wall height was slipping into the measurement. Should be fixed in v0.3.3.
