### ISSUE TITLE
Doesn't work on large maps.

### ISSUE THREAD

**Issue by sonicboom12345** [caewok/fvtt-elevated-vision#38]
Ability to assign elevations does not appear to work on maps larger than ~8000 x 8000 pixels.

**Comment by caewok** [comment]
That does not surprise me. Right now, the elevation layer is using a texture (basically, an image file) equal to the size of the scene. That texture may be uploaded to the GPU, depending on the settings, and is also saved in the Foundry database so elevation scene data is recorded. I don't think I am doing anything to actively prohibit use with a scene that size, but there are several potential fail points.

Does assigning elevations work if you change "Display Elevation Shadows" to "None"? Or to "Polygons"? 

My intention is to eventually transition to something similar to what Foundry does for the fog-of-war, which is to set an upper limit to the texture size and interpolate values. That would help performance on larger maps and potentially fix this particular issue. Unfortunately, interpolation requires more sophisticated handling of the math involved for calculating the elevation locations, so it is not an easy fix.

**Comment by Vralek** [comment]
I also have this issue and changing it to None or Polygons does not change anything. 
I can provide the warnings it generates but there are no errors.

**Comment by caewok** [comment]
Should be fixed in v0.4.0.
