### ISSUE TITLE
Incompatibility with Perfect Vision

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevated-vision#4]
The canvas won't even load while both modules are enabled. I've already reported this issue with Perfect Vision. See the details here: https://github.com/dev7355608/perfect-vision/issues/281

**Comment by caewok** [comment]
Thanks! This one might take awhile. The method in question, `CanvasVisibility.prototype.refresh` is a bit monolithic, and two modules messing with it at once will take some coordination. But I definitely want to get to compatibility with Perfect Vision, so I will look into it!

**Comment by caewok** [comment]
Made some progress on compatibility in v0.1.0. The shadows in lighting appear functional, and the two modules do not throw errors. But the vision shadows are not present. Hopefully this helps as a stop-gap until I can figure out full compatibility!

**Comment by caewok** [comment]
v0.1.5 should have much improved compatibility with Perfect Vision. Please open a new issue if you run into problems!
