### ISSUE TITLE
When GM moves a token, elevation changes as expected, does not change elevation when a player moves their own token

### ISSUE THREAD

**Issue by TogaParty** [caewok/fvtt-elevated-vision#42]
When GM moves a token, elevation changes as expected, does not change elevation when a player moves their own token

Is this a permissions issue?  I can't find any settings in core or in related modules that seems to enable this.

**Comment by TogaParty** [comment]
This doesn't appear to be a consistent issue, perhaps it's related to server performance.

**Comment by LordOHelmet** [comment]
Same issue here.
When the GM moves the token, elevation changes correctly, but not when the player moves the token.
In my case it allways adds +4 in height for the player token. Cleared all Elevated Vision settings from the scene. Reloaded the scene. Made the EV settings again, reloaded scene. But no change.

-Foundry 10.291
-System: GURPS Game Aid 0.15.29
-hosted on the Forge
-active Modules:
![Active Modules](https://user-images.githubusercontent.com/80178910/219596278-43594e58-d853-489f-95ca-1ceeee578d39.JPG)

GM move 01:
![GM move 01](https://user-images.githubusercontent.com/80178910/219596440-b682e1ce-3ef5-412e-9709-e2c1c8e0322d.jpg)

GM move 02:
![GM move 02](https://user-images.githubusercontent.com/80178910/219596567-73fc096e-608f-42ef-8046-8b08a81a84d4.jpg)


Player move 01:
![Player move 01](https://user-images.githubusercontent.com/80178910/219596733-04367b94-1bd0-42be-952d-6f391e3dcd37.jpg)

Player move 02:
![Player move 02](https://user-images.githubusercontent.com/80178910/219596775-c5dd00ff-03e0-43b7-98a6-a1fa019f262c.jpg)

**Comment by caewok** [comment]
Thanks for looking into this! Does Firefox report any warnings or errors in the browser console during all this?

**Comment by LordOHelmet** [comment]
Unfortunately, no error message in Firefox, neither console nor warnings.

**Comment by caewok** [comment]
I think this is fixed in v0.4.0, although I could not tell you why Firefox was doing that. If you still see this issue, please feel free to add a comment or file a new issue.
