### ISSUE TITLE
Error after the update

### ISSUE THREAD

**Issue by Kharmans** [caewok/fvtt-elevated-vision#46]
After update the module to 0.4.0v, the error bellow appears everytime I change maps. In fact, the first time I change maps, the map don't load, only if I do it a second time it load.

![image](https://user-images.githubusercontent.com/112586547/221417696-7e363a52-d221-4834-8969-9fce2db87b1d.png)

**Comment by Kharmans** [comment]
When it load the first time, the same error appears and you cannot do anything on the map, unless you load it a second time. If you don't load it a second time, you can't move any token to the scene, use any control or do anything in that scene.

**Comment by caewok** [comment]
I am unable to replicate that error. Do you have any other modules running? And what browser are you using?

**Comment by Kharmans** [comment]
Well, I don't know why, but I started my server again and the error are not appearing anymore.
Sorry for the false alarm.

**Comment by caewok** [comment]
Thanks for following up!
