### ISSUE TITLE
Permission issues for players after update to v0.4.1

### ISSUE THREAD

**Issue by Vralek** [caewok/fvtt-elevated-vision#47]
When I create an overhead tile and a player logs in, they are getting permission issues.

Ground tiles are fine.

Able to replicate in a fresh environment.

![Elevated_Vision_issue_4012](https://user-images.githubusercontent.com/90917755/221933693-cb58dcbc-61da-441a-85b1-f0667454dcfe.png)
![Issue_4012_version](https://user-images.githubusercontent.com/90917755/221933919-f865eca9-7407-4f0b-855c-13726aead284.png)

**Comment by Vralek** [comment]
![Issue_4012_version2](https://user-images.githubusercontent.com/90917755/221934989-b93e8015-95ae-4efe-861b-afda6e4cef32.png)

**Comment by caewok** [comment]
Is this resolved in 0.4.2? ( Sorry, I am traveling and cannot fully test the fix at the moment.)

**Comment by Vralek** [comment]
> Is this resolved in 0.4.2? ( Sorry, I am traveling and cannot fully test the fix at the moment.)

Can confirm resolved in 0.4.2!
Thanks for the quick fix!
