### ISSUE TITLE
Vision "Shadows" from low obstacles disappear with to many objects / high sight radius

### ISSUE THREAD

**Issue by gordenwunderlich** [caewok/fvtt-elevated-vision#49]
So I have this bush here with a height of 3
![Unbenannt1](https://user-images.githubusercontent.com/7266458/228355038-7772329b-9953-4727-9ff4-da7a5c03b014.png)
and a token with a vision height of 5
![Unbenannt2](https://user-images.githubusercontent.com/7266458/228355300-ec30f3d5-aa87-451b-92be-d966c8ccf967.png)
The bush however does not drop a shadow
![Unbenannt3](https://user-images.githubusercontent.com/7266458/228355588-90aa28f9-5201-4957-90d1-d71164bc489c.png)
Unless I reduce the tokens vision radius
![Unbenannt4](https://user-images.githubusercontent.com/7266458/228355843-faebed29-51e5-4211-873a-ec9932aee395.png)
Now we can see the partial shadow it's supposed to drop
This did also not occur when there were still fewer terrain walls on the map.
tried a bit around since it suddenly stopped working and with all walls set to normal and only the single bush set to limited it worked, but after i changed all walls to limited it only works with limited sight range.

**Comment by caewok** [comment]
How many terrain walls do you have on that map?

**Comment by gordenwunderlich** [comment]
I don't know if there is a way to accurately count them, but each circle seems to be 20 segments, so it should be about 1.800 wall segments.

**Comment by caewok** [comment]
Unfortunately, the current method I am using is to pass the wall data using uniforms in GLSL. There is a hard limit on the number, and going much above 100 tends to result in errors and a complete failure of the lighting shader. This is usually okay for lights (which have limited radius) and limited token vision. Unlimited token vision can quickly hit that limit. 

I am looking into alternatives that may avoid this issue altogether. 

Generally speaking, I am surprised that you get decent performance in Foundry using that many terrain walls. If I remember correctly, there are settings in that module you are using to construct the circular walls to cut back on the number of wall segments it creates. So if you do run into other performance issues, you might consider lowering the number of segments per circle.

**Comment by gordenwunderlich** [comment]
Thanks that explains it.
Performance is (surprisingly) fine. Foundry crashed once when I switched to the walls layer, but I have no Idea why, now it works fine again and moving a token from one end to the other while zoomed out doesn't cause any drops.
You can add/remove wall segments from the circles, but I think you have to do that each time you place one, so not very useful, to reduce the number of walls, if you place like 100 trees
And thanks for looking into it

**Comment by caewok** [comment]
Closing as 0.5 series of Elevated Vision should be better at terrain walls. 1800 may still be too much. Will continue to consider options to make it faster.
