### ISSUE TITLE
"Elevated Vision" prevents "Alternative Token Visibility" from functioning

### ISSUE THREAD

**Issue by rbl047** [caewok/fvtt-elevated-vision#52]
"Alternative Token Visibility" is a module that fixes the token's vision by using its corners instead of its center. Unfortunately, when the "Elevated Vision" module is activated, the "Alternative Token Visibility" module's vision stops working.

**Comment by caewok** [comment]
I am going to need some specifics here. When I use Alt Token Visibility v0.4.5 and Elevated Vision v0.4.5, I don't see any errors. At least, not at first glance. I certainly have not tested all permutations here, so if you can give me more about what the error is and what settings you have enabled, maybe I can track down the issue.

**Comment by rbl047** [comment]
I had "Elevated Vision" v.0.4.2. When I updated to v.0.4.5 the error no longer appeared. Sorry for bothering. Stay up the good work :)

**Comment by caewok** [comment]
Thanks for letting me know!
