### ISSUE TITLE
Elevated Vision interferes with Perfect Vision

### ISSUE THREAD

**Issue by TenguGrib** [caewok/fvtt-elevated-vision#53]
https://user-images.githubusercontent.com/93809766/230990975-63e1642e-d915-4bfa-a107-864ff9ce9656.png
https://user-images.githubusercontent.com/93809766/230991121-eee9763b-416b-4ec3-96c6-79ff0a352562.png

The map has tons of lights, but when the player token is selected, they can see other tokens, but cannot see the terrain or their own token. Problem occurs while both Elevated Vision and Perfect Vision are enabled and does not occur when either one is active on its own. 

https://user-images.githubusercontent.com/93809766/230993581-b1ccd067-9bdb-42ec-8fbc-e167408c9c1c.png
https://user-images.githubusercontent.com/93809766/230993652-8c0b7149-624b-4cce-83fa-abdd8373cc22.png
https://user-images.githubusercontent.com/93809766/230993709-ee06112c-f3b3-4fe5-9fc8-0b7fcdb0af8a.png

**Comment by caewok** [comment]
A few questions to help me narrow this down:

1. What is the minimum elevation in the Scene configuration?
2. Do you have Wall Height enabled, or just EV and PV?
3. Does this occur when you set the Display Elevation Shadows in the Scene configuration to "None"? When you set it to "Polygons"? When you set it to "WebGL"?
4. Does this happen on simpler scenes or just this one?

Thanks!

**Comment by TenguGrib** [comment]
1. Minimum elevation in the Scene config is: 0
2. Yes, wall height is enabled.
3. Ooh, no it doesn't with "None". No with "Polygons." Only "WebGL."
4. I loaded up a simple map with walls, lights, and nothing more, and it does not happen. 
The scene it is occurring on is a Levels enabled map with multiple Token Attacher based assets, layered roofs, and multiple varying wall heights. I can add further details if needed.

**Comment by caewok** [comment]
Sorry, this will not get fixed as Perfect Vision is no longer being updated.
