### ISSUE TITLE
V11 broken

### ISSUE THREAD

**Issue by gioppoluca** [caewok/fvtt-elevated-vision#58]
I know that the module is not yet ready for v11 but just to give a feedback: when activated canvas cannot paint background

**Comment by caewok** [comment]
Yep. Might be a bit longer. v11 broke a lot of stuff for my modules, particularly this one.

**Comment by caewok** [comment]
v0.5.0 brings v11 compatibility. As I noted in the changelog, still a work in progress. All key functionality should be there, but I had to turn off WebGL shadows.
