### ISSUE TITLE
[0.4.8] Saving Elevation as webp is nonfunctional on Forge

### ISSUE THREAD

**Issue by LostCarcosa** [caewok/fvtt-elevated-vision#60]
I'm on 0.4.8. Not sure if this is still an issue on the V11 version of the module, but I'm not seeing anything in the changelogs to indicate that it was fixed.

Essentially, the module tries to save elevation maps to a folder in worlds/[world-id]/assets/elevatedvision/[world-id][scene-id]-elevationMap.webp. 

When saving to the forge, it should ideally be saving to [PATH TO ASSET LIBRARY]/worlds/[...] etc. For example, it should be saving to https://assets.forge-vtt.com/[my forge asset id]/worlds/[world id]/assets/elevatedvision/[world-id]-8FT6dgeVRYHQ8dOz-elevationMap.webp. And sometimes it does!

There's an issue, however, where it will INSTEAD attempt to save to [PATH TO ASSET LIBRARY]/[PATH TO ASSET LIBRARY]/worlds [...]. For example, one of my elevation maps has been stored to 
https://assets.forge-vtt.com/[my forge asset id]/https%3A/assets.forge-vtt.com/[my forge asset id again]/worlds/[world id]/assets/elevatedvision/[world id]-jH8qifo1dZY8qODd-elevationMap.webp

Even more concerningly, it seems able to recurse multiple times- there's one elevation map stored in [Path to assets]/[path to assets]/[path to assets]/world[...]

This issue arose after I updated from 0.4.7. I'm not sure why some elevation maps are stored correctly and others are not.

**Comment by caewok** [comment]
Made some progress with v0.4.9 but I think there is still an issue. It acts like it is saving and loading the elevation data, but it doesn't always record the change. I think it is saving correctly but uploading a cached texture image instead. Still investigating.

**Comment by caewok** [comment]
Should be fixed on v0.5.4. Also backported the fix to v10. Thanks for letting me know!
