### ISSUE TITLE
Bridge Effect Not Working for Tiles (Foundry v11)

### ISSUE THREAD

**Issue by Iakudo** [caewok/fvtt-elevated-vision#62]
Not sure the Elevation settings are working correctly for tiles on v11, since the bridge effect doesn't seem to be functioning as intended. It fades correctly, but doesn't maintain the token's height when walked on, no matter what elevation the token starts from. I'm including screenshots of the settings, but at this point I must have tested just about every possible permutation of relevant setting combinations, elevation ranges for the scene's Levels (with/without overlapping ranges), using walls, not using walls, walls with various combinations of heights, and even different image formats for the tile art. The video showing a bridge on the Elevated Vision page doesn't show what settings are used to make that one work, so I have no idea what I'm doing wrong, if anything.

Ground elevation itself seems to be working fine. It adjusts tokens as expected, but just doesn't seem to care that a tile with an elevation is present under a token, dropping it to the base elevation level.
![noBridge](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/dfa3f474-ad27-47b5-8fb5-0dcee8c4566c)
![tileSettings](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/7c176cf2-727a-4a47-b565-73a73a45cee1)
![installedModules](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/d93222e6-4f5b-4a1d-99c8-1ea1e0a9424a)
![tokenSettings](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/3d7acd0d-295a-47a1-84e2-bca2f0ed6ca7)
![sceneSettings](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/f3127853-2fe0-43fd-b6bc-9c83965a8f83)
![elevated-visionSettings](https://github.com/caewok/fvtt-elevated-vision/assets/139723078/ed8c4b2e-8a76-4ce3-bef4-bbac889ce142)

**Comment by caewok** [comment]
Thanks for the screenshots! Very helpful. Should be fixed in v0.5.5. But please let me know if it is not.

**Comment by Iakudo** [comment]
Thanks, king

**Comment by Iakudo** [comment]
Works now, but with a couple minor issues:
1. A tile _has_ to cover >50% of a grid square with opaque pixels in order to not drop a token.
2. The first time a token attempts to walk on a 'bridge', it will fall through, though subsequent tokens maintain their elevation just fine.

That second one may be fixed with some settings changes, as I'm sure it began after I changed a few things while experimenting to get the bridge working. Will update when I find out what caused it.
