### ISSUE TITLE
Darkvision Active Even with Global Illumination On

### ISSUE THREAD

**Issue by cogito808** [caewok/fvtt-elevated-vision#63]
Foundry Virtual Tabletop: Version 11 Stable, 11.306
Game System: dnd5e, 2.2.2
Browser: Chrome and Firefox

Just upgraded from v10 to the latest v11. On scenes with global illumination on, and the module activated my dark vision characters show mostly in dark vision in non-lighted areas with these weird artifacts that change on zoom. Issue goes away with module disabled. Does not affect characters without dark vision. Not aware of any other modules that effect vision or lighting. Side by side comparison between character with dark vision and one without.

![image](https://github.com/caewok/fvtt-elevated-vision/assets/41975485/ee1060b4-00e5-4d7d-9a8a-88c2f7da59a6)
![image](https://github.com/caewok/fvtt-elevated-vision/assets/41975485/b645262b-8b3e-445b-ae9f-823b77454479)

**Comment by caewok** [comment]
How does this look in v0.5.5?

**Comment by cogito808** [comment]
It seems to have fixed the problem, when only the module itself is loaded. With my usual set of other modules there are some conflicts that is causing the tokens to not to be able to move.

Uncaught TypeError: c.edges.values().next().value is undefined
[Detected 3 packages: elevatedvision, lib-wrapper, levels]
    hasWallCollision RenderedPointSource.js:505
    hasWallCollision RenderedPointSource.js:504
    pointInShadow RenderedPointSource.js:348
    targetInShadow VisionSource.js:79
    _testLOS detection_modes.js:28
    _testLOS#0 libWrapper-wrapper.js:187
    _testPoint detection_modes.js:41
    _testPoint#0 libWrapper-wrapper.js:187
    testVisibility foundry.js:49493
    testVisibility foundry.js:49493
    call_wrapped libWrapper-wrapper.js:507
    registerWrappers wrappers.js:186
    testVisibility#0 libWrapper-wrapper.js:187
    testVisibility foundry.js:38384
    call_wrapped libWrapper-wrapper.js:507
    visibilityWrapper wrappers.js:148
    call_wrapper libWrapper-wrapper.js:616
    testVisibility#0 libWrapper-wrapper.js:189
    get isVisible foundry.js:54461
    call_wrapped libWrapper-wrapper.js:507
    tokenUIWrapperIsVisible uiHandler.js:22
    call_wrapper libWrapper-wrapper.js:616
    isVisible#getter libWrapper-wrapper.js:364
    _refreshVisibility foundry.js:54874
    restrictVisibility foundry.js:38308
    refresh foundry.js:38143
    applyRenderFlags foundry.js:50239
    #applyRenderFlags foundry.js:27654
    emit index.js:89
    update index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
    _tick index.js:89
RenderedPointSource.js:505:32

**Comment by caewok** [comment]
Thanks! I am going to open a new issue about the Levels conflict. Cannot say I am surprised; Levels messes with vision a lot so it is difficult to find solutions that work with it.
