### ISSUE TITLE
Hard Canvas Lock at random innocuous line of sight angles with walls

### ISSUE THREAD

**Issue by GaistH** [caewok/fvtt-elevated-vision#65]
v0.5.5 EV, v9.3 PF1E and v11.306 Foundry

Caught us blindsided, but during our session last night controlling an actor with token vision, the line of sight for specific positions relative to pretty benign wall structures (i.e. mostly straight walls with 4 - 6 nodes) would hard-lock the Canvas -- it would stop updating visually entirely, while the rest of the Foundry UI continued to function fine.  It took extensive repeated keystrokes to deselect an actor to restore canvas control, but we were in an unresolvable state to move said actors until disabling Elevated Vision module, where performance immediately restored to full.

**Comment by caewok** [comment]
Does this still happen in v0.5.8? If so, can you narrow this down? Are you running any modules other than Elevated Vision? What are your EV configuration settings and the scene settings?
