### ISSUE TITLE
Problem with "DUCKING"?

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-elevated-vision#75]
Getting this error with some tokens: 

![CleanShot 2023-08-06 at 12 35 50@2x](https://github.com/caewok/fvtt-elevated-vision/assets/4516034/8ff65cd6-e147-4310-8e3f-963d77692c75)

Not sure what might be going on...

**Comment by caewok** [comment]
Fixed in v0.5.8. It was a check for a Levels property, and if the property did not exist, it was throwing an error.
