### ISSUE TITLE
Full Shadow Penumbra is incompatible with the Limits module

### ISSUE THREAD

**Issue by dev7355608** [caewok/fvtt-elevated-vision#77]
Limits patches [`LightSource#_createPolygon`](https://github.com/dev7355608/limits/blob/b8b2cfde9976c70895f3f6b0dd2b26aab5f1653c/scripts/patches/light.mjs#L6-L14) too. Because of the wrapper registration order EV's `_createPolygon` wrapper wraps around Limits' wrapper and therefore discards the constraint applied to the shape by Limits if *Full Shadow Penumbra* is enabled. If the wrapper order were the other way around, it would throw an error, because EV's `_createPolygon` doesn't return a `PointSourcePolygon` as documented. Limits expects a `PointSourcePolygon`. If EV patched `_getPolygonConfiguration` instead of `_createPolygon`, both problems (order and return type) would be solved. I quickly tested it, and it seemed to work well. The `originalShape` property is no longer set, but it seemed to be unused anyway.

```js
function _getPolygonConfiguration(wrapped) {
  const config = wrapped();
  if ( getSetting(SETTINGS.LIGHTS_FULL_PENUMBRA) ) {
    config.type = "universal";
  }
  return config;
}
```

dev7355608/limits#4

**Comment by caewok** [comment]
Thanks! Fixed in v0.5.8. I forgot that "universal" was a config option, which simplifies things a bit. Presumably Limits is ignoring EV's directional lights, as those also wrap `_createPolygon`.
