### ISSUE TITLE
V11 Object Vision Bug

### ISSUE THREAD

**Issue by Boomer-Kuwanger** [caewok/fvtt-elevated-vision#78]
Currently using v11.306 with DnD5e 2.3.0

Issue:
Tokens and other objects like map notes and door icons are visible through walls for both GM selected tokens on GM client and and player tokens on player client.
![Elevated Vision GM selected token vision bug](https://github.com/caewok/fvtt-elevated-vision/assets/141293626/f565efd2-e188-45d0-982c-920ef8a7690f)

![Elevated Vision Bug GM token vision explored fog](https://github.com/caewok/fvtt-elevated-vision/assets/141293626/ff58af2f-716b-4d07-8ce5-cab941416866)

Expected results:
Walls should correctly test line of sight for objects

![Expected Vision Result](https://github.com/caewok/fvtt-elevated-vision/assets/141293626/f5395fa0-bce1-44df-836b-bdf93268b69a)

How to reproduce:

Make a wall.  Place player token and some other token or object.  Select player token.

![Elevated Vision Bug](https://github.com/caewok/fvtt-elevated-vision/assets/141293626/798e1c8d-1c55-456f-8a72-af8df77068d6)

**Comment by caewok** [comment]
Thanks for the PR! Fixed in v0.5.8.
