### ISSUE TITLE
[Compatibility Issue] Incompatible with Rideables riding height

### ISSUE THREAD

**Issue by Saibot393** [caewok/fvtt-elevated-vision#83]
One of my modules, Rideable, sets the elevation of certain mounted tokens depending on the mounted tokens elevation and height. The problem is, that should the mounted move and get a new elevation through Elevated Vision, so will its riding tokens causing them to appear bellow their mount. I looked at your code a bit and don't think i can easily fix this on my end. 

From what i have seen, your module manipulates the elevation in preUpdateToken call. An easy solution on your end would be to ignore all preUpdateToken calls in which the third parameters has a property RidingMovement == true for the purpose of setting the elevation (see attached image).
![image](https://github.com/caewok/fvtt-elevated-vision/assets/137942782/0a674ae1-af9a-4b4a-9c24-a645f8eceab2)

**Comment by caewok** [comment]
Should be fixed in v0.5.9. I did what you suggested; thanks for that!

**Comment by Saibot393** [comment]
Thank you.

**Comment by Saibot393** [comment]
Sorry to bother you again, i missed the elevation update on refresh in my initial testing. Could you add something like 
`if (game.modules.get("Rideable").active && game.modules.get("Rideable").api.isRider(token.document)) return;` to the refreshTokenHook function in Token.js, i think that should fix the compatibility.
