### ISSUE TITLE
Seeing through walls

### ISSUE THREAD

**Issue by ElroTheOnk** [caewok/fvtt-elevated-vision#88]
I'm having trouble with seeing through walls on a particular map with EV (e.g. the two N-S walls south of the token):
![image](https://github.com/caewok/fvtt-elevated-vision/assets/1310418/c1479345-88c7-419f-b15f-82989632c715)

Wall configuration is as follows:
![image](https://github.com/caewok/fvtt-elevated-vision/assets/1310418/d9504e13-33eb-4ce3-94bd-3dc78d4548a8)

With EV off for reference:
![image](https://github.com/caewok/fvtt-elevated-vision/assets/1310418/c3d566c4-7cb1-485e-be7e-393229719e76)

Let me know if anything else would be useful for troubleshooting - this particular scene is very reliable in this issue (not always with the same walls) while tokens are in the "central square".

**Comment by caewok** [comment]
Could you upload, in a comment here, the scene JSON? (Go to Scenes in the right toolbar, right-click the scene, and select Export Data. Then upload that .json file here.)

**Comment by caewok** [comment]
I looked at this and there is definitely some bug that I need to fix. In the meantime, if you go to the scene configuration and select "Polygons", it should fix the visibility issue.

**Comment by caewok** [comment]
Should be fixed in v0.5.10. Thanks for the help with the scene walls–--that made it a lot easier to debug!
