### ISSUE TITLE
I can't see light sources

### ISSUE THREAD

**Issue by DiegoF824** [caewok/fvtt-elevated-vision#89]
Goodnight. I have a problem regarding light sources. When I place a light source in an elevated area, the light does not appear. It's as if the light is restricted by a wall. In my case, this is only happening with light source - if a token is emanating light, the light will spread across the area normally.

![image](https://github.com/caewok/fvtt-elevated-vision/assets/120662839/3743b649-edb6-475a-b68b-8ecdec6a77e8)

![image](https://github.com/caewok/fvtt-elevated-vision/assets/120662839/07064c80-356b-4129-a14f-d185739dc301)

**Comment by caewok** [comment]
Try going into the light configuration and setting the elevation to some value above the terrain. You might have to move the light around after saving it to force it to refresh, but for me, that makes the light appear.

The light should refresh when you change elevation—I will look into that bug. 

It is difficult to know if a default light is supposed to be at elevation 0 or at elevation infinity. I will look into forcing it to be considered infinitely high, which would help this situation but may cause certain other issues. For example, an infinitely high light does not cause much shadows (depending on if it is exactly overhead, of course) while a light at elevation 0 would cause infinite shadows for most default wall setups.

**Comment by caewok** [comment]
In v0.5.10, I forced infinite lights to use a really large integer for elevation. Conceptually, I think it is more intuitive that lights with infinite elevation are treated as such. We will see if it causes too much confusion, given that Foundry really treats lights as if they are just slightly above the canvas .

**Comment by Jnov36** [comment]
I'm still having this issue.  Fully updated on Foundry and the module.  I tried increasing the height of the light manually but it did not work.  Any idea?
