### ISSUE TITLE
Extreme performance hit while module is enabled

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevated-vision#9]
My frame rate goes from 60 to about 10 as long as the module is enabled. 

dnd5e 2.0.2
Foundry 10.284
Elevated Vision 0.0.2

**Comment by caewok** [comment]
Yes, this is a high priority for me when I get back from vacation in a few weeks. In the meantime, what does your FPS look like with "Apply elevation data to token vision" enabled/disabled? And what processor and GPU are you running? Thanks!

**Comment by caewok** [comment]
If you don't mind, could you install [this preview release](https://github.com/caewok/fvtt-elevated-vision/releases/tag/0.1-alpha) and let me know if you see a performance improvement? 

You may need to remove your current Elevated Vision installation, copy the module.json link, and then paste that link into Foundry's Install Module: Manifest URL text box to install the new release. If you do that, the version should display as 0.1-alpha.

Thanks!

**Comment by Zamrod** [comment]
The performance hit seems to be gone in this version.

**Comment by Zamrod** [comment]
I may have been too hasty. The fps stays high but there is now a significant delay from when you let go of a token to when the token moves back to its original location to start the animation. During that time Foundry is locked up. It doesn't happen every time a token is moved, maybe one in three times.

**Comment by caewok** [comment]
I cannot replicate your issue with the delay when letting go of a token. Please see if v0.1.0 changes this at all. I assume this delay happens when Elevated Vision is loaded, and doesn't happen when just using base Foundry?

**Comment by Zamrod** [comment]
I think it may be an issue with base Foundry. I was playing in a game with
Atropos with nearly no modules and it was happening all the time. But with
a different computer than I was testing your module with. I suspect there's
a core bug. Or an issue with an Nvidia driver.

**Comment by caewok** [comment]
I will close this for now, but if you find this is related to Elevated Vision, please feel free to reopen.
